version: "3.9"

services:
  api:
    build: .
    container_name: recipes-api
    ports:
      - 4000:4000
    volumes:
      - ./:/server
    networks:
      - postgres
    command: ["./wait-for-it.sh", "pg:5432", "--", "npm", "run", "dev"]

  pg:
    image: postgres
    container_name: recipes-pg
    restart: always
    environment:
      POSTGRES_DB: recipes
      POSTGRES_USER: recipes
      POSTGRES_PASSWORD: recipes
    ports:
      - 5432:5432
    networks:
      - postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    networks:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin

networks:
  postgres:
    driver: bridge

volumes:
  pgdata:
  pgadmin:
